### ISSUE TITLE
warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1   lib/oauther.ex:110

### ISSUE THREAD

**Issue by jbhatab** [lexmag/oauther#11]
Just got this warning. Letting you know.

**Comment by lexmag** [comment]
Hey @jbhatab, thanks for reporting.
What version do you use? This warning was fixed in v1.1.0.

**Comment by jbhatab** [comment]
oh I'll upgrade. thanks. im on 1.0.1
