### ISSUE TITLE
Current lib usage and HMAC-256

### ISSUE THREAD

**Issue by cigzigwon** [lexmag/oauther#19]
Hello. In my case I have had to pony up two functions to build OAuth1.0a w/HMAC-256 support. Is there any plan to support that? What do you guys use? I'm having to use this spec to push stuff into Oracle NetSuite. Should I publish a lib? I havent really looked at the code but mine is two functions. One returns the headers and the other does signing. It works with hackney and HTTPoison. Any thoughts help. Possibly just a PR here. Not sure....

**Comment by tmepple** [comment]
Did you get it to work using OAuth 1.0a to hit the NetSuite REST endpoint?  If so then definitely it would be great if you published a lib or shared the gist... as I am trying to get it to work right now.

I found there is an open PR from January intended to add HMAC-256 support but haven't tested it out yet.

**Comment by jrissler** [comment]
@tmepple I've used the HMAC-SHA256 PR in 2 projects so far - seems good.

**Comment by cigzigwon** [comment]
@jrissler I guess that explains where we are at. @tmepple I can gist later if needed. Mine is simple and does work with that API. Ive imported over 60000 records.

**Comment by tmepple** [comment]
@cigzigwon I've been fighting NetSuite all night with this... for some reason I keep getting "Invalid Login Attempt" even though my tokens look good, I'm using the SHA256 PR, and everything works great in Postman with the same keys.

Are you using what they call the "IssueToken Endpoint" or the recommended 3-step flow?

If you have a chance to post a gist that works I would greatly appreciate it.

**Comment by cigzigwon** [comment]
Lets get you unblocked today.

I'm using token based auth. I'll make a gist and send some links. You have
to make a custom role assign it to the I integration and use its secrets.
I'll share more today after I get wired in.

**Comment by cigzigwon** [comment]
@tmepple Sorry got distracted!
[https://gist.github.com/cigzigwon/4ff99b48438d5be85633bdecfd2c2e06](url)

**Comment by cigzigwon** [comment]
@tmepple This guide touches on the security settings. You can't just use Admin. Make a new role and apply it to the account you want to auth with.
[https://help.deputy.com/en/articles/3394347-setting-up-netsuite-token-based-authentication-tba](https://help.deputy.com/en/articles/3394347-setting-up-netsuite-token-based-authentication-tba)

**Comment by lexmag** [comment]
Closed via #15.

I'm sorry for keeping you all waiting.
